SEAT_VACANT = "Vacant"
SEAT_RESERVED = "Reserved"
SEAT_WINDOW = "Window"
SEAT_AISLE = "Aisle"
SEAT_MIDDLE = "Middle"

RESERVATION_CONFIRMED = "Confirmed"
RESERVATION_WAITING_LIST = "WaitingList"
RESERVATION_CANCELLED = "Cancelled"
RESERVATION_NEW = "New"

PASSENGER_SEAT_ALLOCATED = "Allocated"
PASSENGER_SEAT_NOT_ALLOCATED = "Not Allocated"

API_PORT = 2000
